name: build
on: [push]
jobs:
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: gcc -fPIC -lm -shared src/stats.c -o dist/sqlite3-stats.so
